### ISSUE TITLE
difficulty in launching your website from a github repo directory

### ISSUE THREAD

**Issue by akvsak** [derekkedziora/derekkedziora.com#3]
Hi, I found your website while searching for dark mode. It is perfect for my needs. Thanks.

I have forked your website in my repo [https:www.github.com/akvsak/dkwww](https:www.github.com/akvsak/dkwww) and am using GH Pages [https://akvsak.github.io/dkwww](https://akvsak.github.io/dkwww) to launch it.

The current system assumes all the links start from the root of the domain i.e. `akvsak.github.io` instead of `akvsak.github.io/dkwww`

I tried to make the links relative again but still having difficulty in launching the website from `dkwww` directory. I saw other forks where it works well if people launch from root domain ie. `*.github.io`.

From your fork in my repo,
1) I removed your website name from `CNAME`
2) In `_config.yml` I put the url: https://akvsak.github.io/dkwww
3) I tried to remove some hard links from other files also.

I was wondering if there is any quick way to specify the jekyll system to start from `akvsak.github.io/dkwww` instead of `akvsak.github.io`

Thanks.

**Comment by derekkedziora** [comment]
Hi! Sorry, I completely missed this. 

Unfortunately, I also don't know how to handle subdomains, since I've never had to deal with that. Were you able to figure out a solution?

**Comment by akvsak** [comment]
> Hi! Sorry, I completely missed this.
> 
> Unfortunately, I also don't know how to handle subdomains, since I've never had to deal with that. Were you able to figure out a solution?

Let me try all over again and report back to you.

**Comment by derekkedziora** [comment]
I remembered that I do actually use a subdomain with this site, [here’s what the config file looks like](https://github.com/derekkedziora/jekyll-demo/blob/master/_config.yml)

**Comment by akvsak** [comment]
> I remembered that I do actually use a subdomain with this site, [here’s what the config file looks like](https://github.com/derekkedziora/jekyll-demo/blob/master/_config.yml)

wow. thanks so much for the followup. I will try it this weekend. I know such small matters might be cumbersome but grateful for your patience.
